-- CreateEnum
CREATE TYPE "ActivityType" AS ENUM ('STOCK_IN', 'STOCK_OUT', 'STOCK_TRANSFER', 'STOCK_ADJUSTMENT', 'SALE_CREATED', 'SALE_CONFIRMED', 'SALE_DELIVERED', 'SALE_CANCELLED', 'PURCHASE_CREATED', 'PURCHASE_CONFIRMED', 'PURCHASE_DELIVERED', 'EMPLOYEE_CREATED', 'EMPLOYEE_UPDATED', 'INVOICE_CREATED', 'INVOICE_PAID');

-- CreateTable
CREATE TABLE "ActivityLog" (
    "id" TEXT NOT NULL,
    "type" "ActivityType" NOT NULL,
    "actorId" TEXT,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "delta" JSONB,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ActivityLog_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ActivityLog" ADD CONSTRAINT "ActivityLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
